# ===============================
# CONFIGURAÇÕES DO POSTGRESQL
# ===============================
# Como o banco deve estar rodando direto no seu ambiente Linux, o caminho local (localhost) na porta padrão 5432 é o ideal.
# Substitua "uber_db" pelo nome do banco que você criou, e ajuste o username e password.
spring.datasource.url=jdbc:postgresql://localhost:5432/uber_db
spring.datasource.username=postgres
spring.datasource.password=uber

# ===============================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ===============================
# O comando "update" faz a mágica: toda vez que você rodar o projeto, 
# o Spring vai ler suas classes Java e criar/atualizar as tabelas automaticamente no PostgreSQL.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do terminal os comandos SQL que o Hibernate está gerando por baixo dos panos (ótimo para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true